### ISSUE TITLE
The patch change Attack names

### ISSUE THREAD

**Issue by Messij** [Drenn1/pokered-gbc#2]
Hello, thanks for this amazing patch.
I'm trying to create a french version of pokered color. 
I've found the patch here: https://hax.iimarckus.org/topic/3399/
I have fork this repo: https://github.com/pret/pokered to change texts to french
Because this is the only one I can build (yours send me python error) and apply patch to.
Every text changes works fine excepted for attack names under MoveNames::
It look likes these texts are changed by the patch (in B&W the attacks are in french but in color they'r in English)
Any way to avoid it ?
Thanks again

**Comment by Stewmath** [comment]
I'm not sure I understand exactly how you approached this, but here's my suggestion. I would recommend using Danny-E's version of the colorization hack, as it's more up to date, and you may have more luck building it:
https://github.com/dannye/pokered-gbc

There is also a french version of pokered, however it seems that it may also be old and out-of-date. Perhaps you can use parts of it though.
https://github.com/anakojm/pokered-fr

The easiest approach may be to use Danny-E's fork of this hack as a base, and copy certain files from "pokered-fr" into it.

Attempting to apply the IPS patch on top of a modified ROM always has the potential to create problems. Although I'm surprised that it would change attack names (if I understand correctly).

**Comment by Messij** [comment]
Thank you so much for your awnser !! (I wouldn't expect one)
That work great with dannye repo (I don't know why I'd missed it), I forked it and replace the translated files. Now every thing work find with attack name in French.
So I can confirm you that the patch changed the attack name.

**Comment by Stewmath** [comment]
:+1:
